pearl/auth.py
from flask import Blueprint, render_template, request, redirect, session, url_for, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_required, current_user, login_user, logout_user
from . import db
from .models import User, Doctor

auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
    return render_template('login.html')

@auth.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False
    
    if not email or not password:
        flash('Please fill all details', 'error')
        return redirect(url_for('auth.login'))
        
    user = User.query.filter_by(email=email).first()
    
    if not user or not check_password_hash(user.password, password):
        user = Doctor.query.filter_by(email=email).first()
        
        if not user or not check_password_hash(user.password, password):
            flash('Please check your details and try again', 'error')
            return redirect(url_for('auth.login'))
        
        session['role'] = 'doctor'
        session['user_id'] = user.id
        login_user(user, remember=remember)
        
        return redirect(url_for('main.professional'))    
        
    session['role'] ='user'
    session['user_id'] = user.id
    login_user(user, remember=remember)
    
    return redirect(url_for('main.userPanel'))    

@auth.route('/signup')
def signUp():
    return render_template('signUp.html')

@auth.route('/signup', methods=['POST'])
def signUp_post():
    fullname = request.form.get('fullname')
    email = request.form.get('email')
    password = request.form.get('password')
    gender = request.form.get('gender')
    
    user= User.query.filter_by(email=email).first()
    if user:
        flash('Email address already exists', 'error')
        return redirect(url_for('auth.signUp'))
    
    new_user = User(fullname=fullname, email=email, gender=gender, password=generate_password_hash(password, method='pbkdf2:sha256'), role='user')
    
    db.session.add(new_user)
    db.session.commit()
    
    return redirect(url_for('auth.login'))

@auth.route('/professional-signup')
def professionalSignUp():
    return render_template('professionalSignUp.html')

@auth.route('/professional-signup', methods=['POST'])
def professionalSignUp_post():
    fullname = request.form.get('fullname')
    email = request.form.get('email')
    password = request.form.get('password')
    mobile = request.form.get('mobile')
    
    user= Doctor.query.filter_by(email=email).first()
    
    if user:
        flash('Email address already exists', 'error')
        return redirect(url_for('auth.professionalSignUp'))
    
    new_user = Doctor(fullname=fullname, email=email, mobile=mobile, password=generate_password_hash(password, method='pbkdf2:sha256'), role='doctor')
    
    db.session.add(new_user)
    db.session.commit()
    
    return redirect(url_for('auth.login'))


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    session.pop('user_id', None)
    session.pop('role', None)
    return redirect(url_for('main.index'))

pearl/main.py
from datetime import datetime
from flask import Blueprint, jsonify, render_template, request, redirect, url_for, flash
from flask_login import current_user, login_required
from .models import Appointment, Survey, User
from . import db
# from .models import OrderItem, Product, Order, OrderDetails

main = Blueprint('main', __name__)

@main.route('/')
def index():
    return render_template('home.html')

@main.route('/home')
def home():
    return render_template('home.html', active_page='home')

@main.route('/survey')
@login_required
def survey():
    questions = [
            "I relapse way too easily in my drinking/smoking habit",
            "I feel sad and unhappy",
            "I have interest and joy in the aspects of my life that were of major importance to me",
            "I feel like I fall in everything I try",
            "I have difficulty in concentration and making of decisions",
            "I got constant anxiety and panic attacks",
            "I am agitated and keep moving around",
            "I am constantly looking over my shoulder in fear",
            "I feel like the urge to move on from my negative thought is lacking",
            "I live too much in my head, creating negative ideas, thoughts that will only bring me harm",
            "I feel fatigued",
            "I feel trapped or caught",
            "Most of the times I am broke I get mad"
        ]
    return render_template('survey.html', active_page='survey', questions=questions, enumerate=enumerate)

@main.route('/professional')
@login_required
def professional():
    return render_template('professional.html', active_page='professional')

@main.route('/About')
def About():
    return render_template('About.html', active_page='About')

@main.route('/journal')
def journal():
    return render_template('journal.html', active_page='journal')

@main.route('/chat')
def chat():
    return render_template('chat.html', active_page='chat')

@main.route('/appointment/book')
def appointment():
    return render_template('appointment.html', active_page='Appointment')

@main.route('/appointment/doctor')
def doctorAppointment():
    appointments =  Appointment.query.all()
    return render_template('doctorAppointment.html', active_page='doctorAppointment', appointments=appointments)

@main.route('/userpanel')
def userPanel():
    appointments = Appointment.query.filter_by(userId=current_user.id).all()
    return render_template('userpanel.html', active_page='userpanel', appointments=appointments)

@main.route('/doctor/chat-space')
def chatSpace():
    comments = db.session.query(Survey.comment, User.fullname).join(User, Survey.userId == User.id).all()
    return render_template('chatSpace.html', active_page='chatSpace', comments=comments)

pearl/templates/Aside.html
<aside
id="logo-sidebar"
class=" relative border-r fixed top-0 bg-white dark:bg-gray-900 left-0 z-40 w-64 h-screen transition-transform -translate-x-full sm:translate-x-0"
aria-label="Sidebar"
>
<div class="h-full px-3 py-4 overflow-y-auto">
  <h1 class="text-white p-2 flex font-bold text-xl py-4">Doctor's Panel</h1>
  <ul class="space-y-2 font-medium">
    <li>
      <a
        href="{{url_for('main.About')}}"
        class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
      >
        <svg
          class="w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          fill="currentColor"
          viewBox="0 0 22 21"
        >
          <path
            d="M16.975 11H10V4.025a1 1 0 0 0-1.066-.998 8.5 8.5 0 1 0 9.039 9.039.999.999 0 0 0-1-1.066h.002Z"
          />
          <path
            d="M12.5 0c-.157 0-.311.01-.565.027A1 1 0 0 0 11 1.02V10h8.975a1 1 0 0 0 1-.935c.013-.188.028-.374.028-.565A8.51 8.51 0 0 0 12.5 0Z"
          />
        </svg>
        <span class="ms-3">My information</span>
      </a>
    </li>
    <li>
      <a
        href="{{url_for('main.journal')}}"
        class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
      >
        <svg
          class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          fill="currentColor"
          viewBox="0 0 18 18"
        >
          <path
            d="M6.143 0H1.857A1.857 1.857 0 0 0 0 1.857v4.286C0 7.169.831 8 1.857 8h4.286A1.857 1.857 0 0 0 8 6.143V1.857A1.857 1.857 0 0 0 6.143 0Zm10 0h-4.286A1.857 1.857 0 0 0 10 1.857v4.286C10 7.169 10.831 8 11.857 8h4.286A1.857 1.857 0 0 0 18 6.143V1.857A1.857 1.857 0 0 0 16.143 0Zm-10 10H1.857A1.857 1.857 0 0 0 0 11.857v4.286C0 17.169.831 18 1.857 18h4.286A1.857 1.857 0 0 0 8 16.143v-4.286A1.857 1.857 0 0 0 6.143 10Zm10 0h-4.286A1.857 1.857 0 0 0 10 11.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 18 16.143v-4.286A1.857 1.857 0 0 0 16.143 10Z"
          />
        </svg>
        <span class="flex-1 ms-3 whitespace-nowrap">Journal</span>
      </a>
    </li>
    <li>
      <a
        href="{{url_for('main.chatSpace')}}"
        class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
      >
        <svg
          class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          fill="currentColor"
          viewBox="0 0 20 20"
        >
          <path
            d="m17.418 3.623-.018-.008a6.713 6.713 0 0 0-2.4-.569V2h1a1 1 0 1 0 0-2h-2a1 1 0 0 0-1 1v2H9.89A6.977 6.977 0 0 1 12 8v5h-2V8A5 5 0 1 0 0 8v6a1 1 0 0 0 1 1h8v4a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-4h6a1 1 0 0 0 1-1V8a5 5 0 0 0-2.582-4.377ZM6 12H4a1 1 0 0 1 0-2h2a1 1 0 0 1 0 2Z"
          />
        </svg>
        <span class="flex-1 ms-3 whitespace-nowrap">Chat Space</span>
      </a>
    </li>
    <li>
      <a
        href="{{ url_for('main.doctorAppointment')}}"
        class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
      >
        <svg
          class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          fill="currentColor"
          viewBox="0 0 20 18"
        >
          <path
            d="M14 2a3.963 3.963 0 0 0-1.4.267 6.439 6.439 0 0 1-1.331 6.638A4 4 0 1 0 14 2Zm1 9h-1.264A6.957 6.957 0 0 1 15 15v2a2.97 2.97 0 0 1-.184 1H19a1 1 0 0 0 1-1v-1a5.006 5.006 0 0 0-5-5ZM6.5 9a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9ZM8 10H5a5.006 5.006 0 0 0-5 5v2a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-2a5.006 5.006 0 0 0-5-5Z"
          />
        </svg>
        <span class="flex-1 ms-3 whitespace-nowrap">My Appointments</span>
      </a>
    </li>
    <li>
      <a
        href="#"
        class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
      >
        <svg
          class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          fill="currentColor"
          viewBox="0 0 18 20"
        >
          <path
            d="M17 5.923A1 1 0 0 0 16 5h-3V4a4 4 0 1 0-8 0v1H2a1 1 0 0 0-1 .923L.086 17.846A2 2 0 0 0 2.08 20h13.84a2 2 0 0 0 1.994-2.153L17 5.923ZM7 9a1 1 0 0 1-2 0V7h2v2Zm0-5a2 2 0 1 1 4 0v1H7V4Zm6 5a1 1 0 1 1-2 0V7h2v2Z"
          />
        </svg>
        <span class="flex-1 ms-3 whitespace-nowrap">Patient Survey</span>
      </a>
    </li>
    <li>
      <a
        href="{{url_for('auth.logout')}}"
        class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
      >
        <svg
          class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
          aria-hidden="true"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 18 16"
        >
          <path
            stroke="currentColor"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M1 8h11m0 0L8 4m4 4-4 4m4-11h3a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-3"
          />
        </svg>
        <span class="flex-1 ms-3 whitespace-nowrap">Log Out</span>
      </a>
    </li>
  </ul>
</div>
</aside>

pearl/templates/appointment.html
{% extends 'base.html' %}
{% block title%} Appointment {% endblock%}
{% block head %}
  {{super()}}
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <link rel="stylesheet" href="/static/css/appointment.css">
{%endblock%}
{% block content %}
  <section class="appointmentSection">
    <div class="appointmentContainer">
        <form id="appointmentForm" action="/appointment/book" method="POST">
            <h1> Appointment </h1>
            <div class="appointmentInput">
                <input type="text" name="fullname" placeholder="Full name" pattern="[A-Za-z ]+" required>
            </div>
            <div class="appointmentInput">
                <input type="email" name="email" placeholder="Email" required>
            </div>
            <div class="appointmentInput">   
                <input type="tel" name="telephone" placeholder="Telephone Number" pattern="[0-9]{10}" required>
            </div>
            <div class="appointmentInput">
                <select name="appointmentHours"  required>
                    <option value="" disabled selected class="defaultValue"> Choose appointment hours</option>
                    <option value="8:00am"> 8:00am </option>
                    <option value="11:00am"> 11:00am </option>
                    <option value="2:00pm"> 2:00pm </option>
                    <option value="4:00pm"> 4:00pm </option>
                    <option value="5:30pm"> 6:30pm </option>
                </select>
            </div>
            <div class="appointmentInput">
                <input type="text" id="datepicker" name="date" placeholder=" Choose date" required>
                <input type="submit" value="Submit">
            </div>
        </form>
    </div>
  </section>
  <script>
    $(function() {
        $("#datepicker").datepicker({
            dateFormat: "dd/mm/yy",
            minDate: +1 
        });
    });
  </script>
{%endblock%}

pearl/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title%} {% endblock%}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
    <link rel="stylesheet" href="/static/css/pop.css">
    {% endblock %}
</head>
<body>
    <header>
        <nav class="fixed relative w-full top-0 left-0 text-grey bg-grey-900 bg-grey dark:bg-gray-900 fixed w-full z-20 top-0 start-0 border-b border-gray-200 dark:border-gray-600 py-4 px-6 items-center justify-center align items-center">
            <ul class="flex gap-4 items-center justify-center align items-center text-sm space-x-4">
                <a href="{{url_for('main.home')}}" class="flex mg-left absolute  left-0 px-8 items-stretch self-center">
                    <img src="" class="h-8" alt="">
                    <span class="self-center text-grey text-xl font-semibold whitespace-nowrap dark:text-white self-center">Tubonge Mental Health</span>
                </a>
                {% if not current_user.is_authenticated %}
                <li><a href="{{url_for('main.home')}}"> Home </a></li>
                <li><a href="{{url_for('auth.signUp')}}" class="absolute right-34 top-4" >Sign Up</a></li>
                <li><a href="{{url_for('auth.login')}}" class="bg-grey-500 transition delay-150 duration-300 ease-in-out top-2 flex text-black absolute right-48 bottom-0 space-x-4 px-6 self-center bg-grey-500 hover:bg-white focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-white-600 dark:hover:bg-grey-700 dark:focus:ring-blue-800"><button><i class="fas fa-sign-in-alt"></i> Login as a Doctor</button></a> </li>
                <li><a href="{{url_for('auth.login')}}" class="transition delay-150 duration-300 ease-in-out top-2 flex text-black absolute right-8 bottom-0 space-x-4 px-6 self-center bg-white hover:bg-white focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-white-600 dark:hover:bg-white-700 dark:focus:ring-blue-800">Get started</a> </li>
                {% endif %}
                {% if current_user.is_authenticated %}
                    {% if current_user.role == 'user' %}
                        <li><a href="{{url_for('main.userPanel')}}"> Home </a></li>
                        <li><a href="{{url_for('main.appointment')}}" > Appointment </a></li>
                        <li><a href="{{url_for('main.survey')}}" class="absolute right-34 top-4" > Survey </a></li>
                    {% endif %}
                    {% if current_user.role == 'doctor' %}
                        <li><a href="{{url_for('main.professional')}}"> Home </a></li>
                    {% endif %}
                        <li><a href="{{url_for('auth.logout')}}" class="transition delay-150 duration-300 ease-in-out top-2 flex text-black absolute right-8 bottom-0 space-x-4 px-6 self-center bg-white hover:bg-white focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-white-600 dark:hover:bg-white-700 dark:focus:ring-blue-800">Log out</a> </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <div style="position:relative;">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alertMessage alertMessage-{{category}}">
                        <span>{{ message }}</span>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>
    {% block content %}
    {% endblock %}
    <script>
        window.setTimeout(function() {
            $(".alertMessage").fadeTo(500, 0).slideUp(500, function(){
                $(this).remove(); 
            });
          }, 3000);     
    </script>
</body>
</html>

pearl/templates/professional.html
{% extends 'survey.html' %} {% block title%} Home {% endblock%} {% block head %}
{{super()}} {% endblock %} {% block content %}
<button
  data-drawer-target="logo-sidebar"
  data-drawer-toggle="logo-sidebar"
  aria-controls="logo-sidebar"
  type="button"
  class="inline-flex items-center p-2 mt-2 ms-3 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
>
  <span class="sr-only">Open sidebar</span>
  <svg
    class="w-6 h-6"
    aria-hidden="true"
    fill="currentColor"
    viewBox="0 0 20 20"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      fill-rule="evenodd"
      d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"
    ></path>
  </svg>
</button>
<div class="flex h-screen">
  <aside
    id="logo-sidebar"
    class="relative border-r fixed top-0 bg-white dark:bg-gray-900 left-0 z-40 w-64 h-screen transition-transform -translate-x-full sm:translate-x-0"
    aria-label="Sidebar"
  >
    <div class="h-full px-3 py-4 overflow-y-auto">
      <h1 class="text-white p-2 flex font-bold text-xl py-4">Doctor's Panel</h1>
      <ul class="space-y-2 font-medium">
        <li>
          <a
            href="{{url_for('main.About')}}"
            class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
          >
            <svg
              class="w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
              aria-hidden="true"
              xmlns="http://www.w3.org/2000/svg"
              fill="currentColor"
              viewBox="0 0 22 21"
            >
              <path
                d="M16.975 11H10V4.025a1 1 0 0 0-1.066-.998 8.5 8.5 0 1 0 9.039 9.039.999.999 0 0 0-1-1.066h.002Z"
              />
              <path
                d="M12.5 0c-.157 0-.311.01-.565.027A1 1 0 0 0 11 1.02V10h8.975a1 1 0 0 0 1-.935c.013-.188.028-.374.028-.565A8.51 8.51 0 0 0 12.5 0Z"
              />
            </svg>
            <span class="ms-3">My information</span>
          </a>
        </li>
        <li>
          <a
            href="{{url_for('main.journal')}}"
            class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
          >
            <svg
              class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
              aria-hidden="true"
              xmlns="http://www.w3.org/2000/svg"
              fill="currentColor"
              viewBox="0 0 18 18"
            >
              <path
                d="M6.143 0H1.857A1.857 1.857 0 0 0 0 1.857v4.286C0 7.169.831 8 1.857 8h4.286A1.857 1.857 0 0 0 8 6.143V1.857A1.857 1.857 0 0 0 6.143 0Zm10 0h-4.286A1.857 1.857 0 0 0 10 1.857v4.286C10 7.169 10.831 8 11.857 8h4.286A1.857 1.857 0 0 0 18 6.143V1.857A1.857 1.857 0 0 0 16.143 0Zm-10 10H1.857A1.857 1.857 0 0 0 0 11.857v4.286C0 17.169.831 18 1.857 18h4.286A1.857 1.857 0 0 0 8 16.143v-4.286A1.857 1.857 0 0 0 6.143 10Zm10 0h-4.286A1.857 1.857 0 0 0 10 11.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 18 16.143v-4.286A1.857 1.857 0 0 0 16.143 10Z"
              />
            </svg>
            <span class="flex-1 ms-3 whitespace-nowrap">Journal</span>
          </a>
        </li>
        <li>
          <a
            href="{{url_for('main.chatSpace')}}"
            class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
          >
            <svg
              class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
              aria-hidden="true"
              xmlns="http://www.w3.org/2000/svg"
              fill="currentColor"
              viewBox="0 0 20 20"
            >
              <path
                d="m17.418 3.623-.018-.008a6.713 6.713 0 0 0-2.4-.569V2h1a1 1 0 1 0 0-2h-2a1 1 0 0 0-1 1v2H9.89A6.977 6.977 0 0 1 12 8v5h-2V8A5 5 0 1 0 0 8v6a1 1 0 0 0 1 1h8v4a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-4h6a1 1 0 0 0 1-1V8a5 5 0 0 0-2.582-4.377ZM6 12H4a1 1 0 0 1 0-2h2a1 1 0 0 1 0 2Z"
              />
            </svg>
            <span class="flex-1 ms-3 whitespace-nowrap">Chat Space</span>
          </a>
        </li>
        <li>
          <a
            href="{{ url_for('main.doctorAppointment')}}"
            class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
          >
            <svg
              class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
              aria-hidden="true"
              xmlns="http://www.w3.org/2000/svg"
              fill="currentColor"
              viewBox="0 0 20 18"
            >
              <path
                d="M14 2a3.963 3.963 0 0 0-1.4.267 6.439 6.439 0 0 1-1.331 6.638A4 4 0 1 0 14 2Zm1 9h-1.264A6.957 6.957 0 0 1 15 15v2a2.97 2.97 0 0 1-.184 1H19a1 1 0 0 0 1-1v-1a5.006 5.006 0 0 0-5-5ZM6.5 9a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9ZM8 10H5a5.006 5.006 0 0 0-5 5v2a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-2a5.006 5.006 0 0 0-5-5Z"
              />
            </svg>
            <span class="flex-1 ms-3 whitespace-nowrap">My Appointments</span>
          </a>
        </li>
        <li>
          <a
            href="{{url_for('doctor.getSurveyResults')}}"
            class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
          >
            <svg
              class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
              aria-hidden="true"
              xmlns="http://www.w3.org/2000/svg"
              fill="currentColor"
              viewBox="0 0 18 20"
            >
              <path
                d="M17 5.923A1 1 0 0 0 16 5h-3V4a4 4 0 1 0-8 0v1H2a1 1 0 0 0-1 .923L.086 17.846A2 2 0 0 0 2.08 20h13.84a2 2 0 0 0 1.994-2.153L17 5.923ZM7 9a1 1 0 0 1-2 0V7h2v2Zm0-5a2 2 0 1 1 4 0v1H7V4Zm6 5a1 1 0 1 1-2 0V7h2v2Z"
              />
            </svg>
            <span class="flex-1 ms-3 whitespace-nowrap">Patient Survey</span>
          </a>
        </li>
        <li>
          <a
            href="{{url_for('auth.logout')}}"
            class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
          >
            <svg
              class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
              aria-hidden="true"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 18 16"
            >
              <path
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M1 8h11m0 0L8 4m4 4-4 4m4-11h3a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-3"
              />
            </svg>
            <span class="flex-1 ms-3 whitespace-nowrap">Log Out</span>
          </a>
        </li>
      </ul>
    </div>
  </aside>
<main class="h-screen overflow-y">
  {% block main %}
  <!-- Dynamic content will be here -->
  <div
  class="absolute inset-0 bg-cover object-fit"
  style="
    background-image: url('/static/images/man-being-interviewed-indoors-by-journalist.jpg');
    filter: brightness(50%);
  "
></div>

<!-- Content container -->
<div class="absolute items-center justify-center p-32">
  <!-- Heading -->
  <h1 class="text-white text-4xl font-bold text-center">
    Welcome to our Mental Health Awareness initiative!!!
  </h1>
</div>
  {% endblock %}
</main>
</div> 
{% endblock %}